version: "3.7"
services:
  api:
    build: ./api/
    depends_on:
      - database
    ports:
      - "8000:8000"
    env_file: ./api/.env.local
    restart: always

  database:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  admin_web_interface:
    build: ./admin_web_interface/
    ports:
      - "8008:8008"
    env_file: ./admin_web_interface/.env.local
