version: "3.7"
services:
  api:
    build: ./api/
    depends_on:
      - database
      # - message_queue
    ports:
      - "8000:8000"
    env_file: .env
    restart: always

  database:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  admin_web_interface:
    build: ./admin_web_interface/
    ports:
      - "8080:80"

  # message_queue:
  #   image: rabbitmq:3.8.0-management-alpine
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  # image_worker:
  #   build: ./image_worker/
  #   depends_on:
  #     - message_queue
  #   restart: always
