version: "3.7"
services:
  rest:
    build:
      context: ./api
      dockerfile: ./rest/Dockerfile
    depends_on:
      - database
    ports:
      - "8000:8000"
    env_file: ./api/rest/.env.local
    restart: always

  graphql:
    build:
      context: ./api
      dockerfile: ./graphql/Dockerfile
    depends_on:
      - database
    ports:
      - "4000:4000"
    env_file: ./api/graphql/.env.local
    restart: always

  database:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  admin_web_interface:
    build: ./admin_web_interface/
    ports:
      - "8008:8008"
    env_file: ./admin_web_interface/.env.local
